name: LuckPermsPrefix
authors:
- FaidHD
- ProfessorSam
api-version: 1.18
main: com.github.peddach.luckpermsPrefix.Prefix
version: 1.1.1
description: Add chat prefixes and tablist prefixes from Luckperms
depend:
- LuckPerms
commands:
   prefix: 